### ISSUE TITLE
Longer currency codes

### ISSUE THREAD

**Issue by danaki** [kucharovic/money-bundle#17]
Cryptocurrencies for example MIOTA or WAVES have codes longer than 3 symbols, this number is hardcoded  in `money-bundle/Resources/config/doctrine/Currency.orm.xml`.

**Comment by kucharovic** [comment]
Length of currency code is according to [ISO 4217 standard](https://en.wikipedia.org/wiki/ISO_4217). If you need support of longer symbols, make a pull request, please.

**Comment by danaki** [comment]
There's no reason to stick to this standard in underlying database layer like doctrine, since MoneyPhp supports cryptocurrencies too which do not respect any standards.

**Comment by enumag** [comment]
Agreed, send a PR.
